### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by wanng-ide** [sandy2008/HotelReservationSystem#3]
When I finished an operation, I don't know how to do the next process. The only hint I get is "continue?".
With the function "Admin UI Add", when I input Bed number "1", it is wrong.

**Comment by wanng-ide** [comment]
I think that you can make an EXIT.

**Comment by wanng-ide** [comment]
![issue](https://user-images.githubusercontent.com/32323900/34526603-4cdea55a-f0e6-11e7-930e-682cb6dae480.png)

**Comment by sandy2008** [comment]
fixed
