### ISSUE TITLE
Function "Search" always return "Empty!"

### ISSUE THREAD

**Issue by wanng-ide** [sandy2008/HotelReservationSystem#5]
![image](https://user-images.githubusercontent.com/32323900/34914073-4b7f8870-f94f-11e7-81ea-52ed2730f734.png)

**Comment by wanng-ide** [comment]
And has similar problem with Function 1
![image](https://user-images.githubusercontent.com/32323900/34914005-a5d19cb6-f94d-11e7-81fa-2b0b70f76fa4.png)

**Comment by wanng-ide** [comment]
![image](https://user-images.githubusercontent.com/32323900/34914096-6712b1de-f94f-11e7-9662-60e33edda0e1.png)

**Comment by sandy2008** [comment]
你添加一个预约就不会显示了

**Comment by wanng-ide** [comment]
如果可以的话，还是改进一下下呗
